Fix for CVE-2021-3121
gogo/status pull request #7
Opened 2022-03-11 23:51 UTC by satadrubiswas

CVE https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3121 is fixed in package gogo/protobuf more than year back. This pull request is to ensure that this repo is using the latest version of gogo/protobuf

- Upgrade github.com/gogo/protobuf to v1.3.2 https://github.com/gogo/protobuf/releases/tag/v1.3.2
- Upgrade github.com/golang/protobuf to v1.5.2

2022-03-12 03:05 UTC, johanbrandhorst requested changes
Don't we actually need to regenerate the files as well, not just update the dependency?

2022-03-12 03:05 UTC, johanbrandhorst commented on go.mod
> +	github.com/golang/protobuf v1.5.2
I don't think we can introduce this version, it breaks compatibility with <v1.3.x. Can you revert this version change?

2022-04-20 12:30 UTC, nabbar commented
any news about this update ?
@johanbrandhorst could you make the update of code if necessary ?

2022-04-23 00:40 UTC, johanbrandhorst approved these changes

2022-04-23 00:40 UTC, merged

2022-06-15 01:30 UTC, sahilvv commented
@johanbrandhorst can a new release be cut to be able to consume this change?

2022-06-15 02:26 UTC, johanbrandhorst commented
Thanks for the reminder, I just cut `v1.1.1`.